branch-defaults:
  master:
    environment: gearhead-dev
global:
  application_name: gearhead
  default_ec2_keyname: aws-eb
  default_platform: Node.js
  default_region: us-west-2
  profile: eb-cli
  sc: git
